### ISSUE TITLE
Bitbucket forks are not comparable to github forks

### ISSUE THREAD

**Issue by kmike** [djangopackages-zz/djangopackages#109]
That's because bitbucket counts it as (number of repositories - 1) and github counts it as number of branches. This means that for empty project fork count would be 0 at bitbucket and 1 for github so ego of authors of bitbucket projects is suffering.

I don't know what exactly to do though: live with that, add 1 to bitbucket forks, remove 1 from github forks, add some information to <a>'s title.

**Comment by pydanny** [comment]
Moved to https://github.com/cartwheelweb/packaginator/issues/38#issue/38
