### ISSUE TITLE
Can not sign up / Incorrect code

### ISSUE THREAD

**Issue by gw0** [djangopackages-zz/djangopackages#132]
I was trying to sign up for an account on http://djangopackages.com/account/signup/ and instead of a registration form there is the following:

```
Incorrect Code
You must specify a code.
try again:
```

I also noticed that there is something that evaluates to "None" near the bottom of the page.

**Comment by pydanny** [comment]
We had spammers so had to force people to go to invites only. We plan to have a better way of accepting new accounts by the end of this weekend. If you want an account, please message me privately.

None at the bottom is resolved, we just have to push up the changes.
