### ISSUE TITLE
I get "permission denied" response when trying to add or edit anything.

### ISSUE THREAD

**Issue by fish2000** [djangopackages-zz/djangopackages#133]
Maybe it's just my account -- but it wasn't like that when I joined. My username is 'fish2000'.

"permission denied" is the entirety of the HTTP response body.

**Comment by pydanny** [comment]
We are in the process of a big update so locked things down. We plan to open things up a bit later today. Sorry for the inconvienance.

**Comment by fish2000** [comment]
Aha, no problem then -- thanks.

**Comment by pydanny** [comment]
Actually, your complaint was really useful. We didn't know we were dealing with a DNS propagation issue. Now we know. :)

**Comment by fish2000** [comment]
Haha, always glad to help out and/or complain. You are welcome sir. Good luck with it.

**Comment by pydanny** [comment]
Check out what you are supposed to be seeing. :) http://www.djangopackages.com/grids/g/database-migration/

**Comment by fish2000** [comment]
Hey -- I tried this link a week ago. It looks good but I get the same error... was that what you wanted me to see? just curious. thanks.

**Comment by pydanny** [comment]
Yup. We've had to lock things down because of spam. We'll be changing up authentication shortly.

**Comment by fish2000** [comment]
Aha word, good luck with it, thanks.
