### ISSUE TITLE
http://github.com/ojii/django-login-as breaks add-package form javascript

### ISSUE THREAD

**Issue by ojii** [djangopackages-zz/djangopackages#14]
When putting 'http://github.com/ojii/django-login-as' as repo-url, the slug and pypi-slug field get filled with 'django-login-' instead of 'django-login-as'

**Comment by audreyfeldroy** [comment]
I just tried to repro this and saw it exactly as described in Chrome (8.0.552.215 beta, Ubuntu).  In Firefox (3.6.13, Ubuntu) the slug and pypi-slug do not get filled with anything.  Looking into it now.

**Comment by audreyfeldroy** [comment]
The problem is that URLify removes anything in removelist = ["a", "an", "as", "at", "before", "but", "by", "for", "from",
                  "is", "in", "into", "like", "of", "off", "on", "onto", "per",
                  "since", "than", "the", "this", "that", "to", "up", "via",
                  "with"];

**Comment by audreyfeldroy** [comment]
Fixed by creating a new function DPSlugify that doesn't remove words from removelist.
