### ISSUE TITLE
Search entry on every page

### ISSUE THREAD

**Issue by pydanny** [djangopackages-zz/djangopackages#19]
Cause we don't have a common search field.

**Comment by pydanny** [comment]
Courtesy of Dolugan

**Comment by ptone** [comment]
fix offered in:

https://github.com/ptone/djangopackages/commit/0358750999a15989b229ee1fc850e5ecc9459b4e

with small cleanup in:

https://github.com/ptone/djangopackages/commit/0b34558ff8ccef0fd2c0b84647e7a27f8f23725c
