### ISSUE TITLE
Add 'last update' to packages

### ISSUE THREAD

**Issue by pydanny** [djangopackages-zz/djangopackages#20]
Thanks all who suggested it!

**Comment by ptone** [comment]
So this would be:
- a row in the grid
- a line between repo hostname and repo datatable on package page?

Any other UI comments?

**Comment by gisle** [comment]
Does 'last_update' mean the date of the last commit to source repo, last release or last update to the meta data in djangopackages?

**Comment by pydanny** [comment]
Someone did this yesterday. Just haven't updated the ticket yet!

**Comment by pydanny** [comment]
Need to evaluate and integrate the pull request. Sorry did not mark this as assigned.
