### ISSUE TITLE
HTML renders not so good in Opera

### ISSUE THREAD

**Issue by snaky** [djangopackages-zz/djangopackages#29]
Hi, please check http://djangopackages.com with Opera browser...

**Comment by pydanny** [comment]
We have similar problems with IE users. However, IE and Opera browsers represent a mere 3.23% of our user base, so it is very low priority for us.

However, If you would like to provide fixed code via a pull request I am perfectly happy to test and possibly implement your work. That would make you another contributor!

**Comment by audreyfeldroy** [comment]
It's the lack of CSS3 multi-column support in Opera & IE.  Fixed today and will be deployed soon.

**Comment by snaky** [comment]
GREAT!!! Thanks!!!

**Comment by pydanny** [comment]
Does it look okay in Opera?

**Comment by snaky** [comment]
looks ok!!!
