### ISSUE TITLE
Empty bitbucket account results in a long package list

### ISSUE THREAD

**Issue by vdboor** [djangopackages-zz/djangopackages#32]
When the bitbucket account is empty, my profile displays a long list of packages, suggesting I've written those.

**Comment by pydanny** [comment]
I can't reproduce that error. When I visit your Django Packages page (http://djangopackages.com/profiles/profile/vdboor/) I can't generate the problem. Can you link to the page that is showing this issue?

**Comment by vdboor** [comment]
I've changed my bitbucket account from "-" back to "", and now you can see it:

http://djangopackages.com/profiles/profile/vdboor/

**Comment by psam44** [comment]
Problem is that the default value 'null' in the Profile fields is replaced by an empty string at the first edit form the user.
(note that a null=True on a char field is a bad idea - refer to the django doc)

Empty values should be better managed.

But for a quick repair, in apps / profiles / models.py :
change bitbucket_regex = r'^%s,|,%s,|%s$' % (name, name, name)
to bitbucket_regex = r'^%s,|,%s,|,%s$' % (name, name, name)

and
change github_regex = r'^%s,|,%s,|%s$' % (name, name, name)
to github_regex = r'^%s,|,%s,|,%s$' % (name, name, name)

(add a ',' before the $)

**Comment by pydanny** [comment]
Done!
