### ISSUE TITLE
Allow packages to be tagged

### ISSUE THREAD

**Issue by vdboor** [djangopackages-zz/djangopackages#34]
I've just added `django-flag`, but couldn't find a appropriate grid to display it at.

I think tagging will be a valuable addition to find packages across various topics. (e.g. everything related to social media, or everything related to commenting).

**Comment by pydanny** [comment]
If you can't find the right grid, create a new grid via http://www.djangopackages.com/grids/add/.

We aren't adding tagging. Grids supersedes that system.
