### ISSUE TITLE
Allow screenshots of features

### ISSUE THREAD

**Issue by vdboor** [djangopackages-zz/djangopackages#36]
Many django packages in general are described briefly, making it hard to grasp what the package does. How about promoting the use of screenshots, in order to make it easier to see what a package does?

**Comment by pydanny** [comment]
Who is the actual legal owner of a package and if we can't determine that, how do we keep out porn.

Believe it or not, these are serious questions.

**Comment by vdboor** [comment]
good point, fully understand this might not be implemented!

**Comment by vdboor** [comment]
hmm. would it make sense to extract existing screenshots from the web pages?
(e.g. from github pages after a succesful pull).

**Comment by pydanny** [comment]
So do screenshots of github pages? Pages of code? Or assume that the developers using github/bitbucket and eventually launchpad/sourceforge put up-to-date screen shots and those images get scraped?

Alas, I don't think this will work. Current public repo systems just don't support the functionality we want and don't have an API to support this sort of action.
