### ISSUE TITLE
bitbucket participants not correct

### ISSUE THREAD

**Issue by wkornewald** [djangopackages-zz/djangopackages#38]
The list of bitbucket participants only contains the creator of the repo. Other admins are not listed. Is this information not available or is it just not implemented?

**Comment by pydanny** [comment]
The information is not available from bitbucket. You can see my comment here: 

https://github.com/djangopackages/djangopackages/blob/master/apps/package/handlers/bitbucket.py#L54

I'm exclaiming there that there is no way to get other collaborators via the API or web interface, not without checking the entire commit history. I may do that in a future effort, but my hope is that bitbucket will address the issue on their own.

**Comment by pydanny** [comment]
To finish this:
1. Bug Bitbucket to provide a better API
2. Implement their API change in the bitbucket handler.

**Comment by wkornewald** [comment]
I've bugged them, so part 1 is done. :)

**Comment by pydanny** [comment]
Thanks! Are you here at #pycon? I want to meet!

**Comment by wkornewald** [comment]
Unfortunately, I'm at home learning for my final diploma exams. :( Or actually, I'm watching a movie because the physics formulas are driving me nuts and I need a break. :)
