### ISSUE TITLE
Password reset email text mentions Pinax

### ISSUE THREAD

**Issue by jaap3** [djangopackages-zz/djangopackages#43]
Password reset email body text opens with:

"You're receiving this e-mail becuase you or someone else has requested a password for your user account at Pinax."

This is somewhat confusing.

The subject of the same message is also kind of strang:

"Password reset e-mail sent"

**Comment by pydanny** [comment]
Odd. I thought the settings were properly in place. We'll look into it at the next sprint.

**Comment by pydanny** [comment]
Closed and handled. Thanks!
