### ISSUE TITLE
Password reset confirmation page tells me to email support@example.com

### ISSUE THREAD

**Issue by jaap3** [djangopackages-zz/djangopackages#44]
After filling out the password reset form I get the following message:

"We have sent you an e-mail. If you do not receive it within a few minutes, contact us at support@example.com."

I'm pretty sure I can't contact you guys as support@example.com

**Comment by pydanny** [comment]
Again, I thought the settings were properly in place. Weird! Another nice low hanging bit of fruit for the next sprint.

**Comment by pydanny** [comment]
Corrected! Thanks!
