### ISSUE TITLE
Rename Hierarchical Trees

### ISSUE THREAD

**Issue by tobych** [djangopackages-zz/djangopackages#45]
By definition, a tree is hierarchical, so this looks silly. I suggest you rename the section to "Trees and Graphs", or to be more precise, "Trees and other Graphs".

**Comment by pydanny** [comment]
What slug do you propose to replace hierarchical-trees?

**Comment by tobych** [comment]
trees-and-graphs

**Comment by pydanny** [comment]
Done: 

http://www.djangopackages.com/grids/g/trees-and-graphs/

**Comment by tobych** [comment]
Cool. I think, realistically, it should be just "Trees and Graphs" in the title. Yes, it's more precise to have "other" in there, but think it's over the top. Hope that makes sense!
