### ISSUE TITLE
Horizontal scroll bar is broken, e.g. see the CMS grid

### ISSUE THREAD

**Issue by audreyfeldroy** [djangopackages-zz/djangopackages#47]
bmihelac Bojan Mihelac reports:
@audreyr nice work, but horizontal scroll bar is broken in chrome (see grids)

Probably has to do with the sticky footer http://www.cssstickyfooter.com/

**Comment by bmihelac** [comment]
It actually does not work in firefox and safari too.

If you remove overflow:auto from #main declaration it would work as it should, at least in these three browsers (couldnt check IE). 

```
#main {
    /*overflow: auto;*/
    padding-bottom: 50px;
}
```

Bojan

**Comment by pydanny** [comment]
Fixed!
