### ISSUE TITLE
add a Resources section to package details

### ISSUE THREAD

**Issue by ptone** [djangopackages-zz/djangopackages#57]
simple related model - title, URL

can point to non RTD docs, blogposts, tutorials, demos etc

origin of this idea is that many packages have their initial and often only documentation in an opening blog post

Not sure if there would be problems with signal-to-noise, but as long as this is being curated more or less openly by the django community - I think it would be OK.

**Comment by pydanny** [comment]
The problem with this is the curation is a LOT of work. Just curating the grids and packages in existence is a lot of work. So I'm going to have to refuse this. I do have some ideas that build off of this:
1. You could use the Django Packages API and roll your own site that builds off of it.
2. We ought to have easy-to-find methods to point people to better documenting their projects.
