### ISSUE TITLE
Grid version numbers out of date

### ISSUE THREAD

**Issue by stephenmcd** [djangopackages-zz/djangopackages#60]
Latest version 0.10.6 is shown on:
http://www.djangopackages.com/packages/p/mezzanine/ 

Yet in the grid it's 3 months old:
http://www.djangopackages.com/grids/g/cms/

Cheers,
Steve

**Comment by jamespacileo** [comment]
can you assign this one please?

**Comment by jamespacileo** [comment]
fixed
