### ISSUE TITLE
new packages not showing up on django community rss feed

### ISSUE THREAD

**Issue by amenasse** [djangopackages-zz/djangopackages#63]
I noticed newly added packages added to http://www.djangopackages.com  aren't showing up in the rss feed of New/updated Django packages on  http://www.djangoproject.com/community/

I seem to remember them showing up there previously ?

Thanks
Ant

**Comment by pydanny** [comment]
I'll check on it

**Comment by pydanny** [comment]
Fixed by the djangoproject community
